version: '3'

services:
  application:
    image: web-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - postgres
    volumes:
      - /data/springboot-app  # Volume mount for the application data
  postgres:
    image: postgres
    networks:
      - springboot-db-net
    environment:
      - POSTGRES_USER=itsp  # Correcting environment variable name
      - POSTGRES_PASSWORD=vivek
    volumes:
      - /data/postgres  # Volume mount for the Postgres data

networks:
  springboot-db-net:
